services:
  - type: web
    name: community-connect-project
    env: docker
    plan: free
    region: oregon
    image: ghcr.io/obviouslyadesh/community-connect:latest
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: community-connect-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: BASE_URL
        value: https://community-connect-project.onrender.com
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: FROM_EMAIL
        sync: false
    healthCheckPath: /health

databases:
  - name: community-connect-db
    plan: free
    databaseName: community_connect
    user: community_connect_user